# Name of the form
name: "\U0001F41B Bug Report"

# Description of the form
description: Submit a bug report to help us improve transformers

# The body of the form
body:
  # Textarea for system info
  - type: textarea
    id: system-info
    attributes:
      label: System Info,
      description: Please share your system info with us. You can run the command `transformers-cli env` and copy-paste its output below.
      placeholder: transformers version, platform, python version, ...
    validations:
      required: true

  # Textarea for who can help
  - type: textarea
    id: who-can-help
    attributes:
      label: Who can help?
      description: > 
        Your issue will be replied to more quickly if you can figure out the right person to tag with @
        If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.

        All issues are read by one of the core maintainers, so if you don't know who to tag, just leave this blank and a core maintainer will ping the right person.

        Please tag fewer than 3 people.

      options:
        - text model: @ArthurZucker and @younesbelkada
        - vision models: @amyeroberts
        - speech models: @sanchit-gandhi
        - graph models: @clefourrier

      library:
        - flax: @sanchit-gandhi
        - generate: @gante
        - pipelines: @Narsil
        - tensorflow: @gante and @Rocketknight1
        - tokenizers: @ArthurZucker
        - trainer: @muellerzr and @pacman100

      integration:
        - deepspeed: HF Trainer/Accelerate: @pacman100
        - ray/raytune: @richardliaw, @amogkam
        - Big Model Inference: @SunMarc
        - quantization (bitsandbytes, autogpt): @SunMarc and @yo
